#!/usr/bin/env python3
"""Generate the README coverage table from childcare.db — the only source of truth.

The table was hand-maintained through v0.3 and silently drifted from the data
(NY off by 2,751 providers, TX by 10,212 seats). Generate it, then assert it.

    python3 stats.py            # print the block
    python3 stats.py --check    # exit 1 if README.md disagrees with the DB
    python3 stats.py --write    # rewrite the block in place
"""
import os, re, sqlite3, sys

HERE = os.path.dirname(os.path.abspath(__file__))
DB = os.path.join(HERE, "childcare.db")
README = os.path.join(HERE, "README.md")
BEG, END = "<!-- coverage:begin -->", "<!-- coverage:end -->"

# statuses gap.py treats as not-in-service; keep in sync with gap.INACTIVE
INACTIVE = {"INACTIVE", "CLOSED", "Not Active", "Suspended", "Pending Revocation",
            "Pending Revocation and Denial", "PENDING", "ON PROBATION"}

# display names, keyed by the source string stored in the DB
LABEL = {"HI-DHS (BrowsAPI)": "HI DHS", "VA-DSS (CCAA layers)": "VA (CCAoA layers)",
         "VT-DHCD": "VT (BBF)", "MN-DHS": "MN DHS (HFLV)"}


def block():
    db = sqlite3.connect(f"file:{DB}?mode=ro", uri=True)
    inact = ",".join(f"'{s}'" for s in INACTIVE)
    rows = db.execute(f"""
        SELECT source, max(state), count(*), sum(capacity_total),
               sum(status IS NULL OR status NOT IN ({inact}))
        FROM providers GROUP BY source ORDER BY count(*) DESC""").fetchall()
    tot_p, tot_s = db.execute(
        "SELECT count(*), sum(capacity_total) FROM providers").fetchone()

    out = [BEG, "",
           f"18 machine-verified state/registry sources, "
           f"**{tot_p:,} providers / {tot_s/1e6:.2f}M licensed seats**:", "",
           "| Source | State | Providers | Licensed seats |", "|---|---|---|---|"]
    for src, st, n, seats, active in rows:
        label = LABEL.get(src, src.replace("-", " ", 1))
        st = "NYC" if src.startswith("NYC") else st
        count = f"{n:,}" + (f" ({active:,} active)" if active < n else "")
        out.append(f"| {label} | {st} | {count} | {seats:,} |")
    out += ["",
            "Generated by `stats.py` from `childcare.db`; `stats.py --check` gates "
            "the weekly refresh so this table cannot drift from the data again.",
            "", END]
    return "\n".join(out)


def splice(text, new):
    return re.sub(re.escape(BEG) + r".*?" + re.escape(END), lambda _: new, text, flags=re.S)


if __name__ == "__main__":
    arg = sys.argv[1] if len(sys.argv) > 1 else ""
    new, cur = block(), open(README).read()
    if arg == "--check":
        ok = BEG in cur and splice(cur, new) == cur
        print("README coverage block matches childcare.db" if ok
              else "STALE: README coverage block disagrees with childcare.db "
                   "— run `python3 stats.py --write`")
        sys.exit(0 if ok else 1)
    if arg == "--write":
        open(README, "w").write(splice(cur, new) if BEG in cur else cur)
        print("README coverage block updated")
    else:
        print(new)
